### ISSUE TITLE
[DI-2.4] Display json on table

### ISSUE THREAD

**Issue by jtam360** [MyMood-Alexa/MyMood-Interface#1]
Data from json file should be displayed correctly in the table.
connects #14
child of #14

**Comment by lydarren** [comment]
Setup the database and read straight from there.

**Comment by danqo** [comment]
you can test the UI with local if unsure it's displaying properly, but the end goal is to have it read the json from the database

**Comment by dionwu110** [comment]
Loading the JSON onto the table works as we were able to test it with some sample data.
![LoadJSON.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd46c33298900115251af/125516c66e82c728ace21e0d46c49b9b27a8b086a1abf301b44fff9e2c4533317346f62a7387e77cbe1b2e585a0e46ab41585a4dfbfedb29f3e02e6c981e5ab38532022d8c6853beb2901eb70bbb258f4f82beb58e4ac7ed3a27f5c6.png)

Right now this feature only works on the remote server as it will not work locally as browsers do not allow this feature to read local files. 

We will now be working on setting up the database to read from DynamoDB.
