### ISSUE TITLE
[DI-3.2] Download raw json

### ISSUE THREAD

**Issue by jtam360** [MyMood-Alexa/MyMood-Interface#11]
Create a button or display a link that allows researcher to directly download the raw json file.

-Allow researcher accessing the interface to be able to download the results being displayed
child of #15
connects #15

**Comment by dionwu110** [comment]
Added a download button at the bottom of our table that will allow the researcher to download the sessions.json file that is stored in our server.

![downloadButton.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd46c33298900115251af/125516c66e82c728ace21e0d46ec9b8d2d8e8ca88bcbaa57b052fed665043761260ea62864c7b96aea4378030b5b1fa544515a15f4fe892ba3bf3b77d85e5ebbc3714d36976345f3e5db55ea43a82a994e82bcbd8f48c2ef3d21ef8a8a4a36181755.JPG)
