### ISSUE TITLE
[DI-2.5] Test compatibility of sample jsons

### ISSUE THREAD

**Issue by jtam360** [MyMood-Alexa/MyMood-Interface#12]
Test sample jsons to make sure the data is displayed correctly in the table.

-Login should be able to be faked
-Main page should accept and display json data with expanding feature
-Start an AWS account and start testing remotely instead of locally
connects #14
child of #14

**Comment by jtam360** [comment]
The login is able to be faked with a fixed username and password, it redirects the user only when they enter the correct parameters, otherwise we display an error message for them:
![login_demo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd086ff8fbd00122ac6dc/125516c66e82c728ace21e0d46e49b9d2a8cbcad8ae4b001e81fe086264c22703d46f9692584e02abb167a585a564bfd495f5f44f9f08e2cf4b46926984019af80330b2b9b645bf9fa9015ad00b22a8a4a86b1ba824fc1ef382de38e9d02.png)

In the future I am going to try to improve the error message with bootstrap form validation that should look something like this:
![validation_demo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd086ff8fbd00122ac6dc/125516c66e82c728ace21e0d46fe95962a8682bd86e6b17ca058fd9b6b0a65633b0ba92e7391a172fd177a020d0b4afd485d5641adf18e2ba6b335778d0e09b8877f4366846c4ff8e7df46f554f832815d84beb68b49c3ef3b2de4888a4f3d1c0c0ac4.png)

The expanding feature we can demo for now allows the user to select a session id to redirect to a new page which displays the rest of the data, it currently is formatted as such:
![session_demo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd086ff8fbd00122ac6dc/125516c66e82c728ace21e0d46fb9189308b8ca7b0edba4eab1fbcd6395428792c07b7692ac7b629bc407f550e564ba544095743fcf98c22a1b16e72df0a19f1c32f0e2a92624cf5f2d75dad0ba821824584b3bf8d4ac8ed3c25e4838b472c53.png)

The expand alternative we were thinking about is just a button for each row that when clicked would display the rest of the responses and should function like this:
![expand_demo.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd086ff8fbd00122ac6dc/125516c66e82c728ace21e0d46ed8c8a228c87968becb24ce611b2843b492d762a10e17132d0e22bbd462f00565a47a910505844fcfc802ca1e43e25dc4e17ff933c0120996048e6edc00db513bb28814e80b5bb8c44c6ed3f25e08d895d73.jpg)

I got the local database functioning but haven't added the tables/loaded the sample json yet. My laptop insisted on updating windows so I'm waiting for that.

Moving the server remotely I was looking into Amazon EC2 and S3. I wanted to use S3 to test remotely but had second thoughts because I wasn't sure if we can implement the security features we planned. S3 is also specifically for static websites and ours is dynamic. Right now I'm thinking of using S3 for testing.

**Comment by dionwu110** [comment]
We created a server and tested with some sample data in a JSON file that is stored on the server which will display a table listing out the attributes that we need.
![database.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd46c33298900115251af/125516c66e82c728ace21e0d46ec958e228082ba8aabf301b44fff9e2c4533317346f62a7387e77cbe1b2e585a0e46ab41585a4dfbfedb29f3e02e6c981e5ab38532022d8c6853beb2901eb60bbb258f4d82b0b5894bc3ec3d23f5c6.JPG)

Our expanding feature is now that when the researcher clicks on a session ID, they will be able to look at all responses during that session.
![ViewSession.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd46c33298900115251af/125516c66e82c728ace21e0d46de9d9f34b186ba9ce0b04de611b2843b492d762a10e17132d0e22bbd462f00565a47a910505844fcfc802ca1e43e25dc4e17ff933c0120996048e6edc00db513bb28814e80b2be8d4ac9ec3520e18d8b5d73.JPG)
