### ISSUE TITLE
[Deploy-2] Database Interface

### ISSUE THREAD

**Issue by danqo** [MyMood-Alexa/MyMood-Interface#16]
Required for completion:
-Interface is accessible on the web
-Interface accesses MyMood's dynamodb

**Comment by dionwu110** [comment]
The database interface is accessible on the web at: mymood.me

The interface now directly receives data from DynamoDB and stores it in a JSON file on our server which will update every week. Then, the table will read the JSON and display it onto the table.
DynamoDB:
![DynamoDBSS.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd46c33298900115251af/125516c66e82c728ace21e0d46cc8d94228f8c8dadda8c01e81fe086264c22703d46f9692584e02abb167a585a564bfd495f5f44f9f08e2cf4b46926984019af80330b2b9b645bf9fa9015ad00b32a8a4a81b5bf8a4ac7e03c23e68c9d02.JPG)

Our Database:
![database.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd46c33298900115251af/125516c66e82c728ace21e0d46ec958e228082ba8aabf301b44fff9e2c4533317346f62a7387e77cbe1b2e585a0e46ab41585a4dfbfedb29f3e02e6c981e5ab38532022d8c6853beb2901eb80bbb258f4c86b6ba824ec6eb3923f5c6.JPG)
