### ISSUE TITLE
[DI-1.5] Database Interface Login Page

### ISSUE THREAD

**Issue by jtam360** [MyMood-Alexa/MyMood-Interface#5]
Allow a user to log in with a presentable UI with username and login text fields.

-Have a UI ready for the login page
-Screenshots of a working and accepted login page, waiting for backend changes

child of #19
connects #19
requires #21

**Comment by dionwu110** [comment]
Screenshots:

Checks for valid login credentials:
![Login UI.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd46c33298900115251af/125516c66e82c728ace21e0d46c49b9d2a8cc39ca6abf301b44fff9e2c4533317346f62a7387e77cbe1b2e585a0e46ab41585a4dfbfedb29f3e02e6c981e5ab38532022d8c6853beb2901eb80bbb25884883bebb8c44c3ec3524f5c6.JPG)

With valid login credentials, goes to database:
![database.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd46c33298900115251af/125516c66e82c728ace21e0d46ec958e228082ba8aabf301b44fff9e2c4533317346f62a7387e77cbe1b2e585a0e46ab41585a4dfbfedb29f3e02e6c981e5ab38532022d8c6853beb2901eb60bbb25884883bebb8d4ac1e13521f5c6.JPG)
