### ISSUE TITLE
[DI-1.7] Database Interface Help Page

### ISSUE THREAD

**Issue by jtam360** [MyMood-Alexa/MyMood-Interface#7]
Write markup for help page frontend.

-Have a UI ready for the help page
-Screenshots of a working and accepted help page

child of #19
connects #19

**Comment by dionwu110** [comment]
Screenshot of help page:
![help page.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acbd46c33298900115251af/125516c66e82c728ace21e0d46e0919633c293a888ecfd0fe64de29b234324676b5ee17e7186e12ceb432254565a1fa446585f41f5fe8e79a4e36a62964e49bc8f3900299f7744eeaa880dbe09b0218e4c8dbebb824ac6ea3522e299c2.JPG)
